-- MySQL Script generated by MySQL Workbench
-- Sun Jul 12 15:31:08 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema waterford_security
-- -----------------------------------------------------
-- Test for new waterford security db

-- -----------------------------------------------------
-- Schema waterford_security
--
-- Test for new waterford security db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waterford_security` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `waterford_security` ;

-- -----------------------------------------------------
-- Table `waterford_security`.`Client_DB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterford_security`.`Client_DB` (
  `Client_Name` VARCHAR(200) NULL COMMENT '',
  `Address` VARCHAR(200) NULL COMMENT '',
  `Contact_Number` INT NULL COMMENT '',
  `Contact_Person` TINYTEXT NULL COMMENT '',
  PRIMARY KEY (`Client_Name`)  COMMENT '',
  UNIQUE INDEX `Job Number_UNIQUE` (`Client_Name` ASC, `Address` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterford_security`.`Main_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterford_security`.`Main_Table` (
  `Job_number` INT NULL AUTO_INCREMENT COMMENT '',
  `Job_Type` TINYTEXT NULL COMMENT '',
  `Time_start` DATETIME NULL COMMENT '',
  `Time_finish` DATETIME NULL COMMENT '',
  `Client` VARCHAR(200) NULL COMMENT '',
  `Technician` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`Job_number`)  COMMENT '',
  UNIQUE INDEX `Job number_UNIQUE` (`Job_number` ASC)  COMMENT '',
  INDEX `Client_idx` (`Client` ASC)  COMMENT '',
  CONSTRAINT `Client`
    FOREIGN KEY (`Client`)
    REFERENCES `waterford_security`.`Client_DB` (`Client_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterford_security`.`Job_Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterford_security`.`Job_Comment` (
  `Job_Number` INT NULL COMMENT '',
  `Tech_Comment` LONGTEXT NULL COMMENT '',
  `Job_task` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`Job_Number`)  COMMENT '',
  UNIQUE INDEX `Job Number_UNIQUE` (`Job_Number` ASC)  COMMENT '',
  CONSTRAINT `Job Number Link 1`
    FOREIGN KEY (`Job_Number`)
    REFERENCES `waterford_security`.`Main_Table` (`Job_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waterford_security`.`material_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waterford_security`.`material_order` (
  `Order_number` BIGINT(20) NOT NULL COMMENT '',
  `Job_Number` INT NOT NULL COMMENT '',
  `Supplier` TINYTEXT NULL COMMENT '',
  `Item` MEDIUMTEXT NULL COMMENT '',
  `Price` REAL NULL COMMENT '',
  PRIMARY KEY (`Order_number`)  COMMENT '',
  INDEX `Job Number Link_idx` (`Job_Number` ASC)  COMMENT '',
  UNIQUE INDEX `Order number_UNIQUE` (`Order_number` ASC)  COMMENT '',
  UNIQUE INDEX `Job Number_UNIQUE` (`Job_Number` ASC)  COMMENT '',
  CONSTRAINT `Job Number Link 2`
    FOREIGN KEY (`Job_Number`)
    REFERENCES `waterford_security`.`Main_Table` (`Job_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `waterford_security` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `waterford_security`$$
$$

DELIMITER ;

FLUSH PRIVILEGES;
CREATE USER 'fred'@'localhost' IDENTIFIED BY 'root';

GRANT ALL ON `waterford_security`.* TO 'fred';
CREATE USER 'alex'@'localhost' IDENTIFIED BY 'root';

GRANT ALL ON `waterford_security`.* TO 'alex';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
